# Generated by Django 3.1.7 on 2023-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('cam_url', models.CharField(max_length=100)),
                ('cam_name', models.CharField(max_length=100)),
            ],
        ),
    ]
