# Generated by Django 3.1.7 on 2023-02-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_auto_20230216_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraset',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cameraset',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
